name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: volta-cli/action@v1

      - name: Install Renovate CLI
        run: yarn global add renovate

      - name: Validate renovate.json
        run: renovate-config-validator
