name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Get cache dirs
        id: cache-dirs
        run: |
          echo "::set-output name=cache-dir::$(yarn cache dir)"
          echo "::set-output name=global-dir::$(yarn global dir)"
          echo "::set-output name=global-bin::$(yarn global bin)"

      - name: Cache Deps
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.cache-dirs.outputs.cache-dir }}
            ${{ steps.cache-dirs.outputs.global-dir }}
            ${{ steps.cache-dirs.outputs.global-bin }}
          key: ${{ runner.os }}-renovate-config-validator

      - name: Install Renovate CLI
        run: yarn global add renovate

      - name: Validate renovate.json
        run: renovate-config-validator
